### ISSUE TITLE
Internal Server Error - Image Upload to Media Library 

### ISSUE THREAD

**Issue by areddy01** [john-smilga/strapi-gatsby-porfolio-2020-api#2]
Hi John,

While uploading images to Media Library getting "AssertionError [ERR_ASSERTION]: Cannot wrap non-Error object" Internal Server Error. 

In network tab I noticed , /upload call is failing . Attaching screen shot for same .

![image](https://user-images.githubusercontent.com/3590244/84720526-e1203f00-af9b-11ea-8351-cf29de6ca2b1.png)

Thankyou,
Aditya

**Comment by john-smilga** [comment]
Hello,
When you open the project in the code editor is the following file present?
./extensions/upload/config/settings.json
